export enum Status {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
  CLOSED = 'CLOSED'
}

export enum LoginType {
  PASSWORD, SECURITY_CODE, SMART_OTP
}

export enum PackageType {
  TIME = 'TIME',
  USER = 'USER',
  SUBDOMAIN = 'SUBDOMAIN',
  PORT = 'PORT'
}

export enum LocalKey {
  EN = 'en',
  VI = 'vi',
}

export enum Role {
  SYSTEM = 'system',
  ADMIN = 'ROLE_ADMIN',
  USER = 'user',
  All = 'all'
}

export enum ROLES {
  ADMIN = 'ADMIN',
  USER = 'USER'
}

export enum EventName {
  RELYING_PARTY_GET_ACCESS_TOKEN = "RELYING_PARTY_GET_ACCESS_TOKEN",
  RELYING_PARTY_UPDATE_INFO = "RELYING_PARTY_UPDATE_INFO",
  RELYING_PARTY_CREATE_USER = "RELYING_PARTY_CREATE_USER",
  RELYING_PARTY_DELETE_USER = "RELYING_PARTY_DELETE_USER",
  RELYING_PARTY_UPDATE_AUTHENTICATOR = "RELYING_PARTY_UPDATE_AUTHENTICATOR",
  RELYING_PARTY_DELETE_AUTHENTICATOR = "RELYING_PARTY_DELETE_AUTHENTICATOR",
  // RELYING_PARTY_ATTESTATION_OPTIONS = "RELYING_PARTY_ATTESTATION_OPTIONS",
  // RELYING_PARTY_ATTESTATION_RESULT = "RELYING_PARTY_ATTESTATION_RESULT",
  // RELYING_PARTY_ASSERTION_OPTIONS = "RELYING_PARTY_ASSERTION_OPTIONS",
  // RELYING_PARTY_ASSERTION_RESULT = "RELYING_PARTY_ASSERTION_RESULT"
}

export enum EventType {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  AUTHENTICATION = "AUTHENTICATION"
}

export enum EventStatus {
  SUCCESS = "SUCCESS",
  FAILURE = "FAILURE"
}